{"version":3,"sources":["../../app-src/util/ApplicationException.js"],"names":["ApplicationException","Error","constructor","message","name","exception","isApplicationException","err","Object","getPrototypeOf","getExceptionMessage","console","log"],"mappings":";;;;;;gBAAaA,oB,GAAN,MAAMA,oBAAN,SAAmCC,KAAnC,CAAyC;AAC5CC,4BAAYC,UAAU,EAAtB,EAA0B;AACtB,0BAAMA,OAAN;;AAEA,yBAAKC,IAAL,GAAY,KAAKF,WAAL,CAAiBE,IAA7B;AACH;AAL2C,a;;;;AAQhD,kBAAMC,YAAYL,oBAAlB;;AAEO,qBAASM,sBAAT,CAAgCC,GAAhC,EAAqC;AACxC,uBAAOA,eAAeF,SAAf,IACHG,OAAOC,cAAP,CAAsBF,GAAtB,aAAsCF,SAD1C;AAEH;;;;AAEM,qBAASK,mBAAT,CAA6BH,GAA7B,EAAkC;AACrC,oBAAID,uBAAuBC,GAAvB,CAAJ,EACI,OAAOA,IAAIJ,OAAX,CADJ,KAEK;AACDQ,4BAAQC,GAAR,CAAYL,GAAZ;AACA,2BAAO,sCAAP;AACH;AACJ","file":"ApplicationException.js","sourcesContent":["export class ApplicationException extends Error {\n    constructor(message = '') {\n        super(message);\n\n        this.name = this.constructor.name;\n    }\n}\n\nconst exception = ApplicationException;\n\nexport function isApplicationException(err) {\n    return err instanceof exception || \n        Object.getPrototypeOf(err) instanceof exception;\n}\n\nexport function getExceptionMessage(err) {\n    if (isApplicationException(err))\n        return err.message;\n    else {\n        console.log(err);\n        return 'Não foi possível realizar a operção.';\n    }\n}"]}